### ISSUE TITLE
A typo in vocaset stage2.yaml?  What is "wav_mini"?

### ISSUE THREAD

**Issue by YifengMa9** [Doubiiu/CodeTalker#59]
Thanks for your remarkable work.

In stage2.yaml
```
DATA:
  dataset: vocaset
  data_root: ./vocaset/
  wav_path: wav_mini
  vertices_path: vertices_npy
```
Should `wav_path` be `wav`, not `wav_mini` ?
